import localFont from 'next/font/local'
import './globals.css'
import { AvatarProvider } from '../context/AvatarContext'
import ProductContextProvider from '../context/ProductContext'
import { FavoriteProductsProvider } from '../context/FavoriteProductsContext'
import Sidebar from '../helper/Sidebar'

const PlusJakartaSans = localFont({
  src: '../../public//fonts/PlusJakartaSans-VariableFont_wght.ttf'
})

export const metadata = {
  title: 'PointPlus | | Food delivery easy, efficient, and enjoyable',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <body className={`${PlusJakartaSans.className}`}>
        <AvatarProvider>
          <ProductContextProvider>
            <FavoriteProductsProvider>
              <main className='flex w-full'>
                <Sidebar />
                <div className="Routes overflow-y-scroll ml-0 max-h-[calc(100vh)] w-[100%]">
                  {children}
                  </div>
              </main>
            </FavoriteProductsProvider>
          </ProductContextProvider>
        </AvatarProvider>
      </body>
    </html>
  )
}
